import React, { useState, useEffect } from 'react';
import {
 Card,
 Form,
 Input,
 Button,
 Switch,
 Typography,
 Space,
 message,
 Popover,
 Divider,
} from 'antd';
import {
 LockOutlined,
 EyeOutlined,
 EyeInvisibleOutlined,
 InfoCircleOutlined,
} from '@ant-design/icons';
import axios from 'axios';
import { useTranslation } from '../../../context/TranslationContext';
import { useReservation } from '../../../hooks/useReservation';

const { Title, Text } = Typography;

const ElectronicLockCodeManager = ({
 reservationId,
 initialLockEnabled = false,
 initialLockCode = null,
}) => {
 const { t } = useTranslation();
 const { updateElectronicLock, loading: lockUpdateLoading } = useReservation();
 const [form] = Form.useForm();

 const [lockEnabled, setLockEnabled] = useState(initialLockEnabled);
 const [lockCode, setLockCode] = useState(initialLockCode);
 const [codeVisible, setCodeVisible] = useState(false);
 const [isLoading, setIsLoading] = useState(false);

 useEffect(() => {
  setLockEnabled(initialLockEnabled);
  setLockCode(initialLockCode);

  form.setFieldsValue({
   lockCode: initialLockCode || '',
  });
 }, [initialLockEnabled, initialLockCode, form]);

 const toggleLockEnabled = async (checked) => {
  try {
   setIsLoading(true);

   // If enabling the lock, ensure there's a code or generate one
   let code = lockCode;
   if (checked && !code) {
    code = generateRandomCode();
    setLockCode(code);
    form.setFieldsValue({ lockCode: code });
   }

   // Update the reservation with the new lock settings
   const result = await updateElectronicLock(reservationId, checked, code);

   if (result) {
    setLockEnabled(checked);
    message.success(
     checked
      ? t('reservation.lock.enableSuccess')
      : t('reservation.lock.disableSuccess')
    );
   }
  } catch (error) {
   console.error('Error updating electronic lock settings:', error);
   message.error(t('reservation.lock.updateError'));
  } finally {
   setIsLoading(false);
  }
 };

 const generateRandomCode = () => {
  // Generate a random code (6 digits by default)
  const length = 6; // Default length
  return Math.floor(
   Math.pow(10, length - 1) + Math.random() * 9 * Math.pow(10, length - 1)
  ).toString();
 };

 const handleGenerateCode = () => {
  const newCode = generateRandomCode();
  setLockCode(newCode);
  form.setFieldsValue({ lockCode: newCode });
 };

 const handleCodeChange = (e) => {
  setLockCode(e.target.value);
 };

 const handleSubmit = async () => {
  try {
   await form.validateFields();
   setIsLoading(true);

   // Update only the lock code
   await axios.patch(`/api/v1/reservations/${reservationId}/electronic-lock`, {
    electronicLockCode: lockCode,
    electronicLockEnabled: lockEnabled,
   });

   message.success(t('reservation.lock.codeUpdateSuccess'));
  } catch (error) {
   console.error('Error updating lock code:', error);
   message.error(t('reservation.lock.codeUpdateError'));
  } finally {
   setIsLoading(false);
  }
 };

 // Information content for the Popover
 const lockInfoContent = (
  <div style={{ maxWidth: 300 }}>
   <Text>{t('reservation.lock.infoText')}</Text>
   <ul>
    <li>{t('reservation.lock.autoGeneratedInfo')}</li>
    <li>{t('reservation.lock.validityPeriodInfo')}</li>
    <li>{t('reservation.lock.securityInfo')}</li>
   </ul>
  </div>
 );

 return (
  <Card
   title={
    <Space>
     <LockOutlined />
     <span>{t('reservation.lock.title')}</span>
     <Popover
      content={lockInfoContent}
      title={t('reservation.lock.infoTitle')}
      trigger="click"
     >
      <InfoCircleOutlined style={{ cursor: 'pointer', color: '#1890ff' }} />
     </Popover>
    </Space>
   }
   style={{ marginBottom: 16 }}
  >
   <div style={{ marginBottom: 16 }}>
    <Space>
     <Text>{t('reservation.lock.enabled')}</Text>
     <Switch
      checked={lockEnabled}
      onChange={toggleLockEnabled}
      loading={isLoading}
      className="custom-switch-purple"
     />
     <Text>
      {lockEnabled
       ? t('reservation.lock.active')
       : t('reservation.lock.inactive')}
     </Text>
    </Space>
   </div>

   {lockEnabled && (
    <>
     <Divider />
     <Form form={form} layout="vertical" onFinish={handleSubmit}>
      <Form.Item
       name="lockCode"
       label={t('reservation.lock.code')}
       rules={[
        { required: true, message: t('reservation.lock.codeRequired') },
        {
         pattern: /^\d+$/,
         message: t('reservation.lock.codeFormat'),
        },
        {
         max: 10,
         message: t('reservation.lock.codeMaxLength'),
        },
       ]}
      >
       <Input.Password
        value={lockCode}
        onChange={handleCodeChange}
        placeholder="Access code (max 10 digits)"
        maxLength={10}
        visibilityToggle={{
         visible: codeVisible,
         onVisibleChange: setCodeVisible,
        }}
        addonAfter={
         <Button
          type="text"
          icon={codeVisible ? <EyeInvisibleOutlined /> : <EyeOutlined />}
          onClick={() => setCodeVisible(!codeVisible)}
          style={{ border: 'none', padding: 0 }}
         />
        }
        style={{ width: '100%' }}
       />
      </Form.Item>

      <Space>
       <Button onClick={handleGenerateCode}>
        {t('reservation.lock.generateCode')}
       </Button>
       <Button type="primary" htmlType="submit" loading={isLoading}>
        {t('common.save')}
       </Button>
      </Space>
     </Form>

     {lockCode && (
      <div style={{ marginTop: 16 }}>
       <Text type="secondary">{t('reservation.lock.validityInfo')}</Text>
      </div>
     )}
    </>
   )}
  </Card>
 );
};

export default ElectronicLockCodeManager;
